name: Trigger Jenkins on PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  trigger-jenkins:
    if: github.event.issue.pull_request != null && startsWith(github.event.comment.body, '/ui-testing')
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Job
        run: |
          curl -X POST "http://your-jenkins-url/job/your-job-name/buildWithParameters" \
          --user "jenkins-user:${{ secrets.JENKINS_API_TOKEN }}" \
          --data-urlencode "PR_NUMBER=${{ github.event.issue.number }}" \
          --data-urlencode "BRANCH_NAME=${{ github.event.issue.pull_request.head.ref }}"
